# Generated by Django 3.1.6 on 2022-04-21 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='orderNumber',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
